import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { poppins, integralCF, satoshi } from "./fonts";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${integralCF.variable} ${satoshi.variable} antialiased`}
            >
                <div className="flex items-center justify-between p-4 bg-gray-800 text-white">
                    <div className="flex items-center">Hello</div>
                </div>
                {children}
                <footer className="flex items-center justify-center p-4 bg-gray-800 text-white">
                    <div className="flex items-center">
                        Made with ❤️ by Webwiz
                    </div>
                </footer>
            </body>
        </html>
    );
}
